### ISSUE TITLE
Sugestion about __call method

### ISSUE THREAD

**Issue by juliocoliveira** [N1ghteyes/cpanel-UAPI-php-class#1]
On line 55 you could change 
from:
return json_decode($this->APIcall($name, $arguments[0]));
to:
return json_decode($this->APIcall($name, $arguments[0]), true);
That will return a full array of arrays instead of a object of arrays and objects.

I changed on my local file.

**Comment by N1ghteyes** [comment]
I'll take a look at the implications of doing this against existing code.

**Comment by N1ghteyes** [comment]
Added the ability to pass a bool flag locally, will push with the next release.
