### ISSUE TITLE
No return from API

### ISSUE THREAD

**Issue by marasi** [N1ghteyes/cpanel-UAPI-php-class#11]
Hi, I'm having no return from Cpanel API and WHM 2FA is disable!

My test location file: https://sistemamobile.com.br/includes/hooks/teste.php
The teste.php code:

```
<?php                   
	echo "Cpanel API Test";

	require("mobileSetup/cpaneluapi.class.php"); 
			
	echo "<br>Include, ok";


	//testing...

	
	$CPUSER = "{user}";
	$CPPASS = "{pass}";
	$CPURL = "96.47.227.212"; //96.47.227.212
	
	$cPanel = new cpanelUAPI($CPUSER, $CPPASS, $CPURL); //instantiate the object 'cPanel.example.com'
	$response = $cPanel->uapi->Mysql->get_restrictions(); 
	print_r($response);
		
?>
```

**Comment by N1ghteyes** [comment]
Just a note, Edited to remove user / pass from your post.

Im pretty sure you're using the wrong IP address. A ping to that test URL comes back with 192.185.42.186

So try that one first.

**Comment by marasi** [comment]
Thanks @N1ghteyes, I've got it!

The issue was a misspelling class name. 
From: $cPanel = new cpanel**U**API {wrong}
To: $cPanel = new cpanelAPI {correct}

Thank you very much.
