### ISSUE TITLE
I'm getting no response

### ISSUE THREAD

**Issue by creativejaved** [N1ghteyes/cpanel-UAPI-php-class#12]
I'm trying to get domain info, it is working good but for some accounts it is neither giving response nor throwing error. I checked credentials are valid but API giving no response.
It is very hard to identify cause of issue without response. Please help, Thank you.
```
 try {
            $cPanel = new cpanelAPI($this->username, $this->password, $this->url);
            $response = $cPanel->uapi->DomainInfo->single_domain_data(array('domain' => $this->url));
            print_r($response);die;
        } catch(Exception $e) {
            print_r($e->getMessage());die;
            throw new Exception($e->getMessage());
        }
```

**Comment by N1ghteyes** [comment]
Hi @creativejaved 

Are you seeing anything in the Apache error log? A lack of response would indicate something is completely failing.

If i get a chance in the next day or so i'll see if i can replicate the issue, but in the mean time, if you have any errors that would be a good place to start.

Thanks

**Comment by creativejaved** [comment]
Hey @N1ghteyes 

I checked for Apache error log, and it is empty.
You can see [test](https://app.amzneos.com/test-cpanel) url I have created to check above code.

Thank you

**Comment by N1ghteyes** [comment]
@creativejaved 

I just had a dig in the WHM docs, I can't actually find any modules / calls for DomainInfo or single_domain_data, which would explain the blank response (I admit i should add some better error checking through)

What info are you trying to retrieve?

**Comment by creativejaved** [comment]
@N1ghteyes 

You can check [single_domain_data](https://documentation.cpanel.net/display/DD/UAPI+Functions+-+DomainInfo%3A%3Asingle_domain_data) URL to see what I'm trying for.

As I mentioned earlier it is working fine but having this issue on few cPanel accounts.

Thank you.

**Comment by N1ghteyes** [comment]
what do you get if you do $cpanel->getError(); after making the call?

so:

```php
 try {
            $cPanel = new cpanelAPI($this->username, $this->password, $this->url);
            $response = $cPanel->uapi->DomainInfo->single_domain_data(array('domain' => $this->url));
            print_r($cpanel->getError());
            print_r($response);die;
        } catch(Exception $e) {
            print_r($e->getMessage());die;
            throw new Exception($e->getMessage());
        }
```

**Comment by creativejaved** [comment]
@N1ghteyes 

I just updated code, you can see the output [here](https://app.amzneos.com/test-cpanel)

**Comment by N1ghteyes** [comment]
Ah ok, so the request is redirected.

What happens if you do:

```php
try {
            $cPanel = new cpanelAPI($this->username, $this->password, $this->url);
            $cPanel->maxredirect= 5;
            $response = $cPanel->uapi->DomainInfo->single_domain_data(array('domain' => $this->url));
            print_r($cpanel->getError());
            print_r($response);die;
        } catch(Exception $e) {
            print_r($e->getMessage());die;
            throw new Exception($e->getMessage());
        }
```

**Comment by creativejaved** [comment]
@N1ghteyes 

Code is updated, still showing same error response. see [here](https://app.amzneos.com/test-cpanel)

Thank you.

**Comment by N1ghteyes** [comment]
I assume you've tried to manually login with the user/pass details you're using?

**Comment by creativejaved** [comment]
@N1ghteyes 

Yes, I have tried many times with user/pass details you can see [here](https://www.useloom.com/share/a83a728253694856b4e9dcbf3dbd97d3)

Thank you

**Comment by N1ghteyes** [comment]
Could you try the same account info, but a different method? Just to check its not something in cPanel blocking access to a specific call.

I.e.

```php
try {
            $cPanel = new cpanelAPI($this->username, $this->password, $this->url);
            $cPanel->maxredirect= 5;
            $response = $cPanel->uapi->Mysql->get_server_information();
            print_r($cpanel->getError());
            print_r($response);die;
        } catch(Exception $e) {
            print_r($e->getMessage());die;
            throw new Exception($e->getMessage());
        }
```

**Comment by creativejaved** [comment]
@N1ghteyes 

Yes, I tried the above method but still the same issue.

**Comment by N1ghteyes** [comment]
Ok, that would suggest that either the user / pass are wrong or something in the firewall is blocking the request.

The only thing i can really suggest here is that you send me access info etc (email or slack would work) so i can check and test, but that's entirely up to you, i appreciate its not ideal.

Either way, i think we can be pretty sure the issue isn't the class itself, its configuration or access permissions.

**Comment by creativejaved** [comment]
@N1ghteyes 
Thank you for your help,
The issue was resolved, It was a firewall issue, Invert port was enabled and outward port was disabled.
