### ISSUE TITLE
Cannot access protected property cpanelAPI::$scope

### ISSUE THREAD

**Issue by Brent72** [N1ghteyes/cpanel-UAPI-php-class#13]
I can't seem to find helpful info on this error - hope someone can help.

The troublesome line is $uapi->scope = $username.'_Mysql';  where $username is my cpanel username.

I also had to change the example instantiation line from 
$uapi = new cpanelUAPI(  to 
$uapi = new cpanelAPI(  because there is no cpanelUAPI class in cpaneluapi.class.php

any ideas?

**Comment by N1ghteyes** [comment]
@Brent72 - what are you specifically trying to achieve?

The usage is as follows:

```php
$api = new cpanelAPI($username, $password, $url);
$api->uapi->Mysql->get_server_information();
```

You can't access scope directly, instead you set it by treating it like an object property.

**Comment by Brent72** [comment]
Thanks for the quick response. 
The example in the repo seems to be incorrect. Line 26 is as follows:
`$uapi->scope = 'Mysql'; // set the scope to the module we want to use. NOTE: this IS case sensitive.`
That was where I was tripping up.

**Comment by N1ghteyes** [comment]
@Brent72 Ah, that's my bad. The readme has been updated since those changes were made, but i guess the examples haven't been.

I'll add it to the list of things to sort ASAP.

Any other issues? or can i close this one? :)

**Comment by Brent72** [comment]
Yeah - thanks close this one.

Kind regards...
Brent.

**Comment by tiagocaus** [comment]
> @Brent72 Ah, that's my bad. The readme has been updated since those changes were made, but i guess the examples haven't been.
> 
> I'll add it to the list of things to sort ASAP.
> 
> Any other issues? or can i close this one? :)

Hello, will you update when?

I'm in doubt of what is correct ... lol
