### ISSUE TITLE
Secret validation on constructor 

### ISSUE THREAD

**Issue by Ribeiro-Tiago** [N1ghteyes/cpanel-UAPI-php-class#14]
Shouldn't the constructor be `if ($secret) {  ...  }` instead of  `if ($this->secret) {  ...  }` ?

**Comment by N1ghteyes** [comment]
Huh.

I can't believe that was missed. Nice spot, i'll push a quick fix now.

**Comment by N1ghteyes** [comment]
Fix is pushed

Thanks for that.
