### ISSUE TITLE
Backup files to an other server

### ISSUE THREAD

**Issue by cacacobra** [N1ghteyes/cpanel-UAPI-php-class#15]
Hi!

I have an array of my WHM websites (host, user, pass), i need to host a script in my root server, that reads the array and send the generated backups to another FTP Server.

I used to do this with "xmlapi", and access with Cron, but my host updated cPanel so it stopped running.

Is it possible with UAPI and this class? Could you help to build it?

**Comment by cacacobra** [comment]
Hello, i managed to build what i wanted, i will post a pastebin link in case someone needs.

But basicly it runs an array with FTP servers and fires a Fullbackup of them to another server. The access is made with Cron.

In case someone finds out my code sucks, and wish to contribute, no problem, i don´t mind....My code is missing some things that i can´t deal right now.

Thanks to N1ghteyes, this class is great, saved me some pain.

PS: Sorry for any bad writing, my english kinda sucks :P


https://pastebin.com/kbXjtBq8

**Comment by N1ghteyes** [comment]
@cacacobra Thanks for this :). As you've solved the question yourself, i'll mark this as closed.
