### ISSUE TITLE
Fatal error: Cannot access protected property cpanelAPI::$scope

### ISSUE THREAD

**Issue by tiagocaus** [N1ghteyes/cpanel-UAPI-php-class#16]
Fatal error: Cannot access protected property cpanelAPI::$scope

**Comment by N1ghteyes** [comment]
@tiagocaus sorry - examples update pushed (its been done for a while but it seems i got sidetracked...)

The README.md file is the most up to date resource for this code, so follow that.

Does that solve the issue for you?

**Comment by tiagocaus** [comment]
I tried this:

```
require "cpaneluapi.class.php";

$cPanel = new cpanelAPI($host_usuario, $host_senha, 'cpanel.xxxx.com');

$response = $cPanel->create_database(['name' => 'db']);
var_dump($response);
```

This error appeared:

> Fatal error: Uncaught exception 'Exception' with message '$this->api is not set or is incorrectly set. The only available options are 'uapi' or 'api2'' in /home1/tstesit/public_html/INSTALAR/cpaneluapi.class.php:166 Stack trace: #0 /home1/tstesit/public_html/INSTALAR/cpaneluapi.class.php(141): cpanelAPI->APIcall('create_database', Array) #1 /home1/tstesit/public_html/INSTALAR/instalar.php(34): cpanelAPI->__call('create_database', Array) #2 /home1/tstesit/public_html/INSTALAR/instalar.php(34): cpanelAPI->create_database(Array) #3 {main} thrown in /home1/tstesit/public_html/INSTALAR/cpaneluapi.class.php on line 166

**Comment by tiagocaus** [comment]
I also tried this, but it also does not create the database and no error appears.

```
require "cpaneluapi.class.php";

$uapi = new cpanelAPI($host_usuario, $host_senha, 'cpanel.xxxx.net');

$database = $nome_bancodedados;
$databaseuser = $user_bancodedados;
$databasepass = $pass_bancodedados;

$uapi->uapi->Mysql->create_database(array('name' => $database));
$uapi->uapi->Mysql->create_user(array('name' => $databaseuser, 'password' => $databasepass));

$uapi->uapi->Mysql->set_privileges_on_database(array('user' => $databaseuser, 'database' => $database, 'privileges' => 'ALL'));
```

**Comment by N1ghteyes** [comment]
Ok, So questions:

1) The class assumes https by default. If you're connecting with http then you'll need to change the ssl flag to 0
2) Have you dumped the $uapi variable? there is an error array that might contain something useful, or you can assign the result of each call to a variable and dump that. If you're not getting any errors but nothing is happening, it could be an issue connecting to the endpoint specifically.
3) Do you have 2 factor auth enabled?

**Comment by N1ghteyes** [comment]
Closing as no further responses. feel free to re-open if needed though.
