### ISSUE TITLE
It possible to add namespace?

### ISSUE THREAD

**Issue by LeCanardNoir** [N1ghteyes/cpanel-UAPI-php-class#17]

**Comment by N1ghteyes** [comment]
Hi @LeCanardNoir 

For the moment not on this class, however you can use the API Core class to achieve the same thing, that is fully namespaced.

https://github.com/N1ghteyes/apicore

An example of the UAPI with it (untested):

```
<?php
include "../vendor/autoload.php";

use n1ghteyes\apicore\client

$api = new client();
$api->setServer("server.cpanel.com");
$api->setVersion("1.1", FALSE);
$api->setBasePath('execute'); //this is for UAPI, for API2 you need to change this to 'json-api/cpanel'
$api->auth('user', 'pass');

$response = $api->POST->Mysql->create_database(['name' => $cPanel->user.'_MyDatabase']);
?>
```

**Comment by LeCanardNoir** [comment]
Thank you for the answer, i build a class exactly like this one with a namespace and use GuzzleHttp\Client.

Thank
