### ISSUE TITLE
is it possible to login to cPanel interface?

### ISSUE THREAD

**Issue by yashodhank** [N1ghteyes/cpanel-UAPI-php-class#18]
Hello,

Is it possible to login to cpanel interface to implement similar to single sign-on using this class when you dont have access to whm (only cPanel username & password)?

Thanks

**Comment by N1ghteyes** [comment]
@yashodhank good question - never tried it. You should be able to set the server / port to cPanel and make requests to it, i dont remember off the top of my head whats supported via that route. 

You might have better luck using the API Core class ( https://github.com/N1ghteyes/apicore ) for that though.

If you're looking to set active browser sessions and use the class to login with the click of a button for example, then you wont be able to use either of those classes. In that instance, your best bet would be to use something to open the cPanel login page, scrape it, fill the form and submit it.

**Comment by yashodhank** [comment]
Thank you so much.. :)
