### ISSUE TITLE
is it possible to delete a database using the uapi?

### ISSUE THREAD

**Issue by kvvaradha** [N1ghteyes/cpanel-UAPI-php-class#20]
Hi, 

this is definitely a great class to extended the api library and make the job easier. 
I have successfully used and i can able to create database and set privilages to it. 

Now i am looking for the delete option to remove the database. Is it possible to remove database from the uapi ?

**Comment by N1ghteyes** [comment]
Hi @kvvaradha 

you certainly can do, UAPI documentation is here: https://documentation.cpanel.net/display/DD/UAPI+Functions+-+Mysql%3A%3Adelete_database

so follow the same pattern as creating a database but replace the method with ->delete_database($databaseName)

**Comment by kvvaradha** [comment]
thank you. it will be great help for me
