### ISSUE TITLE
Third param doesn't accept array

### ISSUE THREAD

**Issue by grahams2020** [N1ghteyes/cpanel-UAPI-php-class#3]
Hi, I noticed when trying to use install_ssl using the uapi, which requires the third param to be an array (rather than another string) the library code errors out. 

Can't quite figure out how to adapt the curl request to format an array of items.

**Comment by N1ghteyes** [comment]
Hmm, i might have to add an extra flag or something, i'll take a look.

**Comment by grahams2020** [comment]
Thanks man, i tried it myself with the code below, this is the foreach loop in the APIcall();

foreach ($arguments as $key => $value) {
        if(is_array($value)){
            $arrayval = null;
            foreach($value as $val){
                $arrayval .= $key . "=" . $val  . "&";
            }
            $this->requestUrl .= $key . "=" . $arrayval . "&";
        }
        else{
            $this->requestUrl .= $key . "=" . $value . "&";
        }
    }

But it still doesn't seem to be passing through properly. I'm not quite sure how this is packaged up to make the curl request

**Comment by N1ghteyes** [comment]
@grahams2020 the docs have all Params as a string:
https://documentation.cpanel.net/display/SDK/UAPI+Functions+-+SSL%3A%3Ainstall_ssl

Am i missing something here? (i haven't had caffeine yet this morning sooo...)

**Comment by grahams2020** [comment]
Ah, i've been staring at this for hours and only just realised my mistake. There's nothing wrong with your library mate - works great
