### ISSUE TITLE
Encoding Url

### ISSUE THREAD

**Issue by phpcore** [N1ghteyes/cpanel-UAPI-php-class#4]
Hi;

In some cases, for example for the cron module (Api v2) the command may contains white spaces. Example: 

> $action =  array(
>         'command'        => 'php -c /home/xxx/php.ini /home/xxx/public_html/app/cron/instance/backup.php',
>         'day'            => '*',
>         'hour'           => '18',
>         'minute'         => '0',
>         'month'          => '*',
>         'weekday'        => '*',
>     );
> //$cron will contains the response in an array (not an object)
> //so the mix of these functions: json_decode(json_encode($OBJECT), true)
> //do the magic :D 
> $cron = json_decode(json_encode($cpapi2->api2->Cron->add_line($action)), true);
> print_r($cron);

So the code of the method "APIcall" should be:

`  protected function APIcall($name, $arguments){
   ....
    foreach ($arguments as $key => $value) {
      $this->requestUrl .= "&" . $key . "=" . urlencode($value);
    }
   ...
  }
`

**Comment by N1ghteyes** [comment]
Thanks @phpcore I'll review and roll into the class as soon as i get a spare moment.

**Comment by N1ghteyes** [comment]
Whoops, took me a while to remember this. The change has been made and pushed.

Thanks!
