### ISSUE TITLE
$uapi->Fileman->upload_files reult You must specify at least one file to upload

### ISSUE THREAD

**Issue by mshannaq** [N1ghteyes/cpanel-UAPI-php-class#6]
While I run the code
$uapi= new cpanelAPI("user","pass","remote.server");
$response = $uapi->Fileman->upload_files(['dir'=>"public_html","file-1" => "/var/file.zip");

the $response looks like

(
--
  | [data] => stdClass Object
  | (
  | [failed] => 0
  | [warned] => 0
  | [uploads] => Array
  | (
  | )
  |  
  | [succeeded] => 0
  | )
  |  
  | [status] => 0
  | [errors] => Array
  | (
  | [0] => You must specify at least one file to upload.
  | )
  |  
  | [messages] =>
  | [metadata] => stdClass Object
  | (
  | )
  |  
  | )
`

how should we do to let the class upload files from the local server to the cpanel server.

**Comment by N1ghteyes** [comment]
Hi mshannaq,

If you're trying to upload a new file, you want to use the save_file_content function. The documentation for the upload_files function is incorrect and the function itself doesn't seem to work in the way expected (Targeted files must already exist in the /tmp dir on the server).

To upload a new file try:

`$result = $uapi->uapi->Fileman->save_file_content([
    'dir' =>"public_html",
    "file" => "file.zip",
    "content" => file_get_contents("/var/file.zip")
]);`

I'll ask the cPanel team if they can update / fix the docs for upload_file

**Comment by mshannaq** [comment]
I used  the save_file_content  function as you said in the above example but if the uploaded file size is small then its uploaded  okay without problem. but if I upload large file (e.g 10MB+) the $result returns NULL

I double check the php configuration of the  local server which runs uapi script as

upload_max_filesize and post_max_size is 40M

but the $result still return NULL and the file not uploaded

so do you think this issue related to the Cpanel?

**Comment by N1ghteyes** [comment]
@mshannaq I've just merged in a pull request that may solve your issues. Let me know.

**Comment by Deltik** [comment]
[UAPI `Fileman::upload_files`](https://documentation.cpanel.net/display/SDK/UAPI+Functions+-+Fileman%3A%3Aupload_files) functionality was made possible in #7.

Example usage:

```php
$cPanel = new cpanelAPI($username, $password, $hostname);
$cPanel->uapi->post->Fileman
       ->upload_files(['dir' => REMOTE_PATH_RELATIVE_TO_HOME,
                       'file-1' => new CURLFile(LOCAL_PATH_TO_FILE)
                       ]);
```

**Note:** Call the `post()` magic method after `uapi()`.

It would be best to add an example like this to the documentation.

**Comment by N1ghteyes** [comment]
@Deltik Agreed, you're welcome to add it in and submit a pull request if you like. I need to sort out the examples folder / general documentation anyway, the MySQL example is old and no longer valid, and i need to add other stuff.

proper documentation is on the list of things to do, but tbh its a time thing.

**Comment by Deltik** [comment]
@N1ghteyes: #8 updates the documentation with usage of the new `cpanelAPI` class.

**Comment by N1ghteyes** [comment]
@Deltik Thanks - I'll close this issue off as complete.

**Comment by eduarguz** [comment]
I was trying to update files by my own using api tokens and guzzle but it is impossible, 
does anyone know how could I replace the Curl "CurlFile" with a guzzle multipart form?
